### ISSUE TITLE
Implement Root-style Reputation Tracks - [closed]

### ISSUE THREAD

**Issue by asacolips** [asacolips-projects/pbta#132]
In GitLab by @n1xx1 on Nov 30, 2022, 10:17

_Merges master -> master_

I implemented something similar to Root's RPG reputation tracks. Basically it tracks 3 values, the actual bonus you get (`.value`) and two other values (`.negative.value` and `.positive.value`) that represent how close you are from changing the actual bonus. It's marked as draft because I didn't handle the diffing yet, and maybe something else I forgot.

![image](https://gitlab.com/asacolips-projects/foundry-mods/pbta/uploads/ba91e56aeda8c8af35212f87362bcdb7/image.png)

![image](https://gitlab.com/asacolips-projects/foundry-mods/pbta/uploads/76ec749d6d78709b32a14b8fb08400cc/image.png)

In Root it works like this: you have a Reputation (`.value`), Notoriety (`.negative.value`) and Prestige (`.positive.value`). Basically Notoriety and Prestige are two clocks that go in different direction. Every time you reach a certain threshold with your Notoriety/Prestige you increase/decrease the Reputation, and clear the Notoriety/Prestige. This threshold depends on the actual Reputation. If the Reputation is 0, then this threshold would be the steps of the Notoriety/Prestige tracks (so 3/5), but, if it is +1, then the thresholds become 3/10, if it's +2 it's 3/15. Likewise if the value is -1 the thresholds are 6/5. This behavior is automated.

The default configuration is:

```toml
  [character.attributesTop.reputationField]
    type = "Track"
    label = ""
    default = 0
    [character.attributesTop.reputationField.negative]    
      label = ""
      steps = 3
      max = 3
      default = 0
    [character.attributesTop.reputationField.positive]
      label = ""
      steps = 5
      max = 3
      default = 0
```

Hopefully it's common enough to make it into the system, but to be honest I don't know of any other game that has a similar subsystem.

Also, in Root you have multiple of these tracks for every faction you interact with. So eventually I may make a new pull request to support Lists of Tracks.
