### ISSUE TITLE
Code Modernization - [merged]

### ISSUE THREAD

**Issue by asacolips** [asacolips-projects/pbta#156]
In GitLab by @mclemente on Nov 22, 2023, 21:54

_Merges beta -> master_

Closes #74.

- Added image to items based on their types.
- Added tooltips to Lists (Closes #67). See 1.
- Added Roll class extension (Closes #32).
- Added CombatTracker and Combatant classes.
- Added Character-type actors being created with Actor Link on (Closes #37).
- Improvements on the Combat tab, such as core Foundry features and some visual changes.
- Visual improvements for actor sheets that don't use the Top or Left attributes.
- Changed the Window Title for document names being uppercased.
- Changed PbtA Sheet Configuration's icon on Settings dialog to be the same as the one on the sidebar.
- Fixed button labels being black on a dark background on popout sidebars (e.g. Macros Directory, right-clicked sidebar tabs).
- Fixed removing an option from a ListOne/ListMany wouldn't remove it from actors.
- Fixed hovering over a Move without a roll would show a Book icon instead of the Chat icon.
- Fixed Tag's icon having a white background.
- Replaced Roll validation for Foundry's.
- Replaced isEmpty function for Foundry's.
- Removed Other-type actor sheets in favor of using their Character/NPC counterparts (Closes #89).
- Removed the monkeypatch to `ActorDirectory.prototype._onCreateEntry` in favor of using Foundry's default actor creation dialog.

## Notes
1. This adds TOML support for List options and Move types to be set as objects. The example code below will create both conditions, with `Foo` having a tooltip.

```toml
[[character.attributesLeft.harmConditions.options]]
  label = "Stabilized"
  tooltip = ""
        
[[character.attributesLeft.harmConditions.options]]
  label = "Foo"
  tooltip = "Bar"
```
