### ISSUE TITLE
Allow for Disadvantage/Advantage to be used with statToggles

### ISSUE THREAD

**Issue by aMediocreDad** [asacolips-projects/pbta#200]
In games like Stonetop, a "Debility" causes Disadvantage on a roll with that stat. Ideally, this should be configurable in the pbta system itself (right now I have implemented a buggy hack in the Stonetop module).

The syntax for configuration would look like so:
```toml
[statToggle]
  label = "Debility"
  modifier = "dis"
```
