### ISSUE TITLE
Add support for overlapping result ranges

### ISSUE THREAD

**Issue by asacolips** [asacolips-projects/pbta#40]
In GitLab by @Asacolips on Apr 11, 2021, 15:10

## Summary

```toml
[rollResults.failure]
  range = "6-"
  label = "Failure"
  header = true
[rollResults.partial]
  range = "7-9"
  label = "Partial Success"
  header = true
[rollResults.success]
  range = "10+"
  label = "Success!"
  header = true
[rollResults.benefit]
  range = "7+"
  label = "Benefit"
  header = false
[rollResults.complication]
  range = "9-"
  label = "Complication"
  header = false
```

## Labels (do-not-change)

/cc @Asacolips
