### ISSUE TITLE
Allow actor types to have labels in addition to their machine name

### ISSUE THREAD

**Issue by asacolips** [asacolips-projects/pbta#48]
In GitLab by @Asacolips on Jul 9, 2021, 14:49

## Example

```toml
[overlord]
  label = "Overlord"

  [overlord.stats]
    ...
```

## Labels (do-not-change)

/cc @Asacolips
