### ISSUE TITLE
Conditions not applying in some cases

### ISSUE THREAD

**Issue by asacolips** [asacolips-projects/pbta#52]
In GitLab by @Asacolips on Aug 3, 2021, 10:58

## Summary

In the Foundry discord, a user has reported that conditions aren't effecting rolls from either moves or stats, nor is there a pop-up.

## Versions

- Foundry 0.8.8
- PbtA 0.3.0
- Masks Unofficial Module

## TOML Config

```toml
# Configure Rolls
rollFormula = "2d6"
statToggle = "Locked"

# Define roll result ranges.
[rollResults]
  [rollResults.failure]
    range = "6-"
    label = "Complications..."
  [rollResults.partial]
    range = "7-9"
    label = "Partial success"
  [rollResults.success]
    range = "10+"
    label = "Success!"

########################################
## CHARACTERS ##########################
########################################
# Define the character group.
[character]

  # Define stats.
  [character.stats]
    danger = "Danger"
    freak = "Freak"
    savior = "Savior"
    superior = "Superior"
    mundane = "Mundane"

  # Define attributes.
  [character.attributesTop]
    [character.attributesTop.heroName]
      type = "Text"
      label = "Hero Name"
    [character.attributesTop.advances]
      type = "Number"
      label = "Advances"      
    [character.attributesTop.xp]
      type = "Xp"
      label = "Potential"
      max = 5
    [character.attributesTop.momentUnlocked]
      type = "Checkbox"
      label = "Moment of Truth"
      checkboxLabel = "Unlocked"
      default = false

  # Define sidebar details.
  [character.attributesLeft]
    [character.attributesLeft.conditions]
      type = "ListMany"
      label = "Conditions"
      condition = true
      description = "Choose all that apply:"
      options = [
        "Afraid (-2 to engage)",
        "Angry (-2 to comfort)",
        "Guilty (-2 to provoke)",
        "Hopeless (-2 to unleash)",
        "Insecure (-2 to defend)"
      ]
    [character.attributesLeft.look]
      type = "LongText"
      label = "Look"
    [character.attributesLeft.abilities]
      type = "LongText"
      label = "Abilities"
    [character.attributesLeft.influence]
      type = "LongText"
      label = "Influence"
    [character.attributesLeft.moment]
      type = "LongText"
      label = "Moment of Truth"

  # Define groups for moves.
  [character.moveTypes]
    basic = "Basic Moves"
    playbook = "Playbook Moves"
    team = "Team Moves"
    adult = "Adult Moves"

  # Define groups for equipment.

########################################
## NPCS ################################
########################################
# Define stats.
[npc]
  # Define attributes.
  [npc.attributesTop]
    [npc.attributesTop.realName]
      type = "Text"
      label = "Real Name"

  [npc.attributesLeft]
    [npc.attributesLeft.conditions]
      type = "ListMany"
      label = "Conditions"
      description = "Choose all that apply:"
      options = [
        "Afraid",
        "Angry",
        "Guilty",
        "Hopeless",
        "Insecure"
      ]  
    [npc.attributesLeft.drive]
      type = "LongText"
      label = "Drive"
    [npc.attributesLeft.abilities]
      type = "LongText"
      label = "Abilities"
    [npc.attributesLeft.generation]
      type = "Text"
      label = "Generation"  

  # Define logical groups for moves.
  [npc.moveTypes]
    villain = "Villain Moves"
```

## Labels (do-not-change)

/cc @Asacolips
